// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKb04crzvBIOul6J9f-JDQNREwjtEaons',
    appId: '1:144187643457:web:ec7a2620477af7f39a58c0',
    messagingSenderId: '144187643457',
    projectId: 'appdevfinal-90673',
    authDomain: 'appdevfinal-90673.firebaseapp.com',
    storageBucket: 'appdevfinal-90673.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2dogzjI3MGTDVWJJLfY0I_PhuetuBzyE',
    appId: '1:144187643457:android:c05f0b1b94148e629a58c0',
    messagingSenderId: '144187643457',
    projectId: 'appdevfinal-90673',
    storageBucket: 'appdevfinal-90673.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoqvQWsCoW9mGdFfZd11w9Cqi8Euodnnk',
    appId: '1:144187643457:ios:520ba06c305d9ab19a58c0',
    messagingSenderId: '144187643457',
    projectId: 'appdevfinal-90673',
    storageBucket: 'appdevfinal-90673.firebasestorage.app',
    iosBundleId: 'com.example.finalExam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoqvQWsCoW9mGdFfZd11w9Cqi8Euodnnk',
    appId: '1:144187643457:ios:520ba06c305d9ab19a58c0',
    messagingSenderId: '144187643457',
    projectId: 'appdevfinal-90673',
    storageBucket: 'appdevfinal-90673.firebasestorage.app',
    iosBundleId: 'com.example.finalExam',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKb04crzvBIOul6J9f-JDQNREwjtEaons',
    appId: '1:144187643457:web:0484b25ef52a389c9a58c0',
    messagingSenderId: '144187643457',
    projectId: 'appdevfinal-90673',
    authDomain: 'appdevfinal-90673.firebaseapp.com',
    storageBucket: 'appdevfinal-90673.firebasestorage.app',
  );
}
